version: "3.8"

services:
  frontend:
    build:
      context: ./apartment-frontend # Path to the Next.js frontend directory
      args:
        NEXT_PUBLIC_API_URL: http://backend:3001
    ports:
      - "3000:3000" # Exposing frontend on port 3000 (to avoid conflict with backend)
    depends_on:
      - backend # Ensure frontend waits for backend to start
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001 # Environment variable for the API URL

  backend:
    build:
      context: ./apartment-backend # Path to the NestJS backend directory
    environment:
      - DB_HOST=db # Database host (points to the db service defined below)
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=relaestatedb
    ports:
      - "3001:3001" # Exposing backend on port 3001
    depends_on:
      - db # Ensure backend waits for database to start
    command: >
      sh -c "wait-for-it db:5432 -- npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run start:dev"

  db:
    image: postgres:latest # Using the official PostgreSQL image
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=relaestatedb
    ports:
      - "5432:5432" # Exposing DB on port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data

volumes:
  db_data: #
